=== anjali-segu/vegetarian-cowgirl/src/assets/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./src/assets/schemas/recipe.schema.json",
  "title": "Recipe",
  "description": "A recipe on The Vegetarian Cowgirl blog",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "description": "Recipe Title",
      "type": "string"
    },
    "subtitle": {
      "description": "Description above the photo",
      "type": "string"
    },
    "subtitle2": {
      "description": "Description below the photo",
      "type": "string"
    },
    "categories": {
      "description": "Recipe categories for steps",
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "description": "Recipe Category",
          "type": "object",
          "properties": {
            "ingredients": {
              "description": "Recipe ingredients per category",
              "type": "object",
              "patternProperties": {
                "^.+$": {
                  "$ref": "ingredient.schema.json"
                }
              },
              "minProperties": 1
            },
            "steps": {
              "description": "Steps per category",
              "type": "array",
              "items": {
                "description": "Step",
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          },
          "required": [
            "ingredients",
            "steps"
          ]
        }
      },
      "minProperties": 1
    },
    "ingredients": {
      "description": "Recipe ingredients",
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "$ref": "ingredient.schema.json"
        }
      },
      "minProperties": 1
    },
    "steps": {
      "description": "Recipe steps",
      "type": "array",
      "items": {
        "description": "Step",
        "type": "string"
      },
      "uniqueItems": true
    },
    "preptime": {
      "description": "How long it takes to prep ingredients",
      "type": "string"
    },
    "cooktime": {
      "description": "How long it takes to cook ingredients",
      "type": "string"
    },
    "totaltime": {
      "description": "Sum of preptime, cooktime, and any additional time for cooling, etc.",
      "type": "string"
    },
    "serves": {
      "type": "integer",
      "minimum": 0,
      "excludeMinimum": true
    }
  },
  "oneOf": [
    {
      "required": [
        "title",
        "subtitle",
        "subtitle2",
        "categories",
        "preptime",
        "cooktime",
        "totaltime",
        "serves"
      ]
    },
    {
      "required": [
        "title",
        "subtitle",
        "subtitle2",
        "ingredients",
        "steps",
        "preptime",
        "cooktime",
        "totaltime",
        "serves"
      ]
    }
  ],
  "additionalProperties": false
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/pumpkin-pie.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Classic Pumpkin Pie",
    "subtitle": "This pumpkin pie has a perfectly spice creamy filling, a flakey crust that is also tender. Topped with maple whipped cream, this pie is a guaranteed success at Thanksgiving.",
    "subtitle2": "A few things that set this pie apart is the condensed milk and measuring out the spices. Sweetened condensed milk adds a decadent richness to the custard, while measuring the spices instead of using a premixed “pumpkin spice” blend, lets you hit just the right ratio to really highlight the flavors of the canned pumpkin purée.",
    "categories": {
        "Crust":{
            "ingredients": {
                "sugar":{
                    "quantity": 1,
                    "unitTag": "tbsp",
                    "ingredient": "sugar"
                },
                "salt": {
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "salt"
                },
                "flour": {
                    "quantity": 2,
                    "unitTag": "cup",
                    "ingredient": "all-purpose flour"
                },
                "butter": {
                    "quantity": 5,
                    "unitTag": "tbsp",
                    "ingredient": "chilled unsalted butter (cut into pieces)"
                },
                "vegetable-shortening": {
                    "quantity": 3,
                    "unitTag": "tbsp",
                    "ingredient": "chilled vegetable shortening"
                },
                "vinegar": {
                    "quantity": 1,
                    "unitTag": "tbsp",
                    "ingredient": "apple cider vinegar"
                },
                "water":{
                    "quantity": 5.5,
                    "unitTag": "tbsp",
                    "ingredient": "ice water"
                },
                "egg": {
                    "quantity": 1,
                    "unitTag": "egg",
                    "ingredient": "(beaten)"
                }
            }
        },
        "Filling": {
            "ingredients": {
                "sugar": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "white sugar",
                    "override": {
                        "half": "2 tbsp + 2 tsp white sugar"
                    }
                },
                "cinnamon": {
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "ground cinnamon"
                },
                "salt": {
                    "quantity": 0.5,
                    "unitTag": "tsp",
                    "ingredient": "salt"
                },
                "ginger": {
                    "quantity": 0.5,
                    "unitTag": "tsp",
                    "ingredient": "ground ginger"
                },
                "clove": {
                    "quantity": 0.25,
                    "unitTag": "tsp",
                    "ingredient": "ground cloves"
                },
                "nutmeg": {
                    "quantity": 0.25,
                    "unitTag": "tsp",
                    "ingredient": "ground nutmeg"
                },
                "egg": {
                    "quantity": 2,
                    "unitTag": "egg",
                    "ingredient": "(large, room temp, beaten)"
                },
                "egg-yolk":{
                    "quantity": 1,
                    "unitTag": "egg yolk",
                    "ingredient": "(large, room temp, beaten)"
                },
                "pumpkin": {
                    "quantity": 2,
                    "unitTag": "cup",
                    "ingredient": "unsweetened pumpkin puree"
                },
                "condensed-milk": {
                    "quantity": 0.67,
                    "unitTag": "cup",
                    "ingredient": "condensed milk"
                },
                "heavy-cream": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "heavy cream",
                    "override": {
                        "half": "2 tbsp + 2 tsp white sugar"
                    }
                },
                "maple": {
                    "quantity": 2,
                    "unitTag": "tbsp",
                    "ingredient": "maple syrup"
                },
                "vanilla": {
                    "quantity": 2,
                    "unitTag": "tsp",
                    "ingredient": "vanilla extract"
                }
            }
        },
        "Maple Whipped Cream":{
            "ingredients": {
                "maple":{
                    "quantity": 2,
                    "unitTag": "tbsp",
                    "ingredient": "maple syrup"
                },
                "heavy-cream":{
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "heavy cream"
                }
            }
        }
    },
    "steps": [
        "Pulse sugar, salt, and flour in a ^food processor$ until combined. Add butter and vegetable shortening and <b>pulse until mixture resembles a course meal with a few pieces of butter and shortening visible.</b> This takes about <b>15, 1-second pulses</b>. With the motor running drizzle in vinegar and water and pulse until the dough is still crumbly but just holds together when squeezed. <i>(Add an additional 1 tsp of water at a time if necessary, but be careful not to overwork dough.)</i>",
        "Turn out dough onto a work surface. Knead 1-2 times, pressing to incorporate any shaggy pieces of dough. Flatten into a disk and wrap with plastic wrap. <b>Chill for at least 1 hr</b>.",
        "<b>Preheat oven to 425°F</b>. Roll out dough on a lightly floured surface to a <b>14-inch round</b>. Transfer to a ^9-inch pie dish$. Pick up the edges and allow the dough to slump into the dish, letting the excess dough hang over the dish. Trim the dough and leave about a 1-inch overhang. Fold the overhang under, and pinch and crimp. <b>Chill for 30 min in the fridge</b>.",
        "Line dough with ^parchment paper$, leaving some overhang. Fill the ^pie weights or dried beans$. Bake until crust is dry around the edges and just beginning to brown, <b>25 min</b>. Remove the parchment and weights and <b>reduce the oven temperature to 350°F</b>. ^Brush$ inside with egg wash and bake until crust is set and beginning to lightly brown in the center, <b>10 min</b>. Transfer to a ^wire rack$ and let cool.",
        "<b>For the filling</b>, preheat oven to 325°F. ^Whisk$ sugar, cinnamon, salt, ginger, cloves, and nutmeg in a large bowl until no clumps remain. Add eggs, pumpkin, condensed milk, cream, maple syrup, and vanilla. Whisk until smooth. Pour into cooled crust. Bake pie until the edges are set and slightly puffed but the center is dipped down and <b>wobbles like Jell-O, 60-75 min</b>. Transfer to wire rack and let cool for at least 3 hours before slicing",
        "<b>For the maple whipped cream</b>, beat the heavy cream and maple syrup until fluffy texture is reached.",
        "Serve pie with whipped cream."
    ],
    "preptime": "1 hr 30 min",
    "cooktime": "1 hr 35 min",
    "totaltime": "6 hr",
    "serves": 8
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/coffee-syrups.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Coffee Simple Syrups",
    "subtitle": "",
    "subtitle2": "",
    "categories": {
        "Lavender Simple Syrup": {
            "ingredients": {
                "lavender-buds": {
                    "quantity": 3,
                    "unitTag": "tbsp",
                    "ingredient": "lavender buds"
                },
                "sugar": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "sugar"
                },
                "water": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "water"
                }
            }
        },
        "Turmeric Ginger Simple Syrup": {
            "ingredients": {
                "ginger": {
                    "quantity": 3,
                    "unitTag": "tbsp",
                    "ingredient": "grated ginger"
                },
                "sugar": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "sugar"
                },
                "water": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "water"
                },
                "cinnamon": {
                    "quantity": 1,
                    "unitTag": "stick",
                    "ingredient": "cinnamon"
                },
                "cardamom": {
                    "quantity": 2,
                    "unitTag": "pod",
                    "ingredient": "cardamom"
                },
                "turmeric": {
                    "quantity": 1.5,
                    "unitTag": "tsp",
                    "ingredient": "turmeric"
                }
            }
        },
        "Cardamom Honey": {
            "ingredients": {
                "sugar": {
                    "quantity": 2.5,
                    "unitTag": "tbsp",
                    "ingredient": "sugar"
                },
                "honey": {
                    "quantity": 2.5,
                    "unitTag": "tbsp",
                    "ingredient": "honey"
                },
                "water": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "water"
                },
                "cardamom": {
                    "quantity": 5,
                    "unitTag": "pod",
                    "ingredient": "cardamom"
                },
                "cardamom-powder": {
                    "quantity": 1,
                    "unitTag": "tbsp",
                    "ingredient": "cardamom powder"
                },
                "salt": {
                    "quantity": 1,
                    "unitTag": "pinch",
                    "ingredient": "salt"
                }
            }
        },
        "Pecan": {
            "ingredients": {
                "sugar": {
                    "quantity": 0.75,
                    "unitTag": "cup",
                    "ingredient": "sugar"
                },
                "water": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "water"
                },
                "pecan": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "toasted and chopped pecans"
                },
                "salt": {
                    "quantity": 1,
                    "unitTag": "pinch",
                    "ingredient": "salt"
                }
            }
        }
    },
    "steps": [
        "For the lavender simple syrup, put half the lavender buds and all of the water in a ^saucepan$. Bring the mixture to a boil, then add the sugar. Lower the heat so it maintains a gentle boil. Stir until sugar is dissolved. Lower the heat to a simmer and allow to simmer for 15 minutes. Turn of the heat and add the remaining lavender buds. Let the mixture cool, then taste. Steep longer for a stronger taste. Strain out the buds.",
        "For the turmeric ginger simple syrup, heat the water and sugar in a small ^saucepan$ over medium heat. Stir until all of the sugar is dissolved, then add the turmeric, cinnamon, and cardamom. Bring the mixture to a boil, then reduce the heat and simmer for 7 minutes. Remove from heat and stir in the ginger. Allow the mixture cool and then strain.",
        "For the cardamom honey simple syrup, cut the cardamom pods halfway and add to ^saucepan$ with water. Bring the water to boil, then reduce to a very gentle simmer for 10 minutes. Add sugar and salt, while allowing to simmer for another 5 minutes. Remove from heat and add the cardamom powder. Stir and strain.",
        "For the pecan simple syrup, put the sugar and water in a ^saucepan$. Bring the mixture to boil, then add the pecans and salt. Let the mixture simmer for 15 minutes. Remove from heat and let the mixture cool. Strain the mixture.",
        "For espresso based drinks, I typically use 1.5 tsp of the lavender syrup, 2 tsp of the turmeric ginger syrup, 2 tsp of the cardamom honey syrup, and 2 tsp of the pecan syrup. Feel free to adjust based on taste."
     
    ],
    "preptime": "15 minutes",
    "cooktime": "2 hours",
    "totaltime": "2 hours 15 minutes",
    "serves": 16
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/turkish-eggs.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Turkish Eggs",
    "subtitle": "Perfect light meal for anytime of day! The soft cooked eggs compliment greek yogurt topped in a spicy chili brown butter sauce.",
    "subtitle2": "This is a week night classic in my house! Turkish eggs is a simple recipe that comes together in a short amount of time. This recipe also scales up well, so it easy to make for the entire family!",
    "ingredients": {
        "egg": {
            "quantity": 4,
            "unitTag": "egg"
        },
        "yogurt": {
            "quantity": 1,
            "unitTag": "cup",
            "ingredient": "greek yogurt"
        },
        "garlic": {
            "quantity": 1,
            "unitTag": "clove",
            "ingredient": "of garlic"
        },
        "dill": {
            "quantity": 1,
            "unitTag": "tsp",
            "ingredient": "dill"
        },
        "lemon-juice": {
            "quantity": 1,
            "unitTag": "tsp",
            "ingredient": "lemon juice"
        },
        "sea-salt": {
            "ingredient": "flaky sea salt"
        },
        "butter": {
            "quantity": 2,
            "unitTag": "tbsp",
            "ingredient": "butter"
        },
        "chili-powder": {
            "quantity": 0,
            "unitTag": "tsp",
            "ingredient": "(or double) chili powder"
        }
    },
    "steps": [
        "Fill a medium sized pot, halfway with water. Bring the water to a  boil.",
        "In a bowl mix the greek yogurt, lemon juice, a pinch of salt, and minced garlic.",
        "In a small pan, heat the butter until it is browned. Take off from heat. Add the chili powder and mix. Set aside.",
        "Add the eggs to the boiling water. Cook for 5 minutes. Immediately take out of boiling water and put in ice cold water. Peel the eggs and set aside.",
        "Between the plates, split the yogurt mixture. Make a swirl and for the eggs to sit in. Place the eggs evenly among the plates on top of the yogurt. Drizzle the butter chili oil on top of the eggs. Top with dill and flakey sea salt.",
        "Eat immediately with toast points or just on it's own."
    ],
    "preptime": "10 minutes",
    "cooktime": "5 minutes",
    "totaltime": "15 minutes",
    "serves": 2
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/chocolate-brownies.json
{
  "$schema": "../schemas/recipe.schema.json",
  "title": "Fudgiest Brownies",
  "subtitle": "",
  "subtitle2": "",
  "ingredients": {
    "cake-mix": {"quantity": 1, "unitTag": "box", "ingredient": "Betty Crocker Triple Chocolate Fudge Cake Mix"},
    "egg": {"quantity": 2, "unitTag": "egg"},
    "canola-oil": {"quantity": 0.5, "unitTag": "cup", "ingredient": "canola oil"},
    "chocolate-chips": {"quantity": 1, "unitTag": "cup", "ingredient": "chocolate chips or any other candy (ex: Andes)"}
  },
  "steps": [
    "Preheat the oven to 350 degrees F."
  ],
  "preptime": "15 min",
  "cooktime": "23 min",
  "totaltime": "40 min",
  "serves": 16
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/cornbread.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Jalapeno Cheddar Cornbread",
    "subtitle": "This cornbread is buttery, fluffy, and has a nice kick of heat! This is a family favorite every Thanksgiving.",
    "subtitle2": "The cornbread has jalapenos, green onions, and cheddar inside giving it lots of flavor. The soft crumb makes it melt in the mouth. This cornbread always disappears in a day or 2 whenever I make it. ",
    "ingredients": {
        "flour":{
            "quantity": 3,
            "unitTag": "cup",
            "ingredient": "all-purpose flour"
        },
        "cornmeal":{
            "quantity": 1,
            "unitTag": "cup",
            "ingredient": "yellow cornmeal"
        },
        "sugar":{
            "quantity": 0.25,
            "unitTag": "cup",
            "ingredient": "sugar"
        },
        "baking-powder":{
            "quantity": 2,
            "unitTag": "tbsp",
            "ingredient": "baking powder"
        },
        "salt":{
            "quantity": 2,
            "unitTag": "tsp",
            "ingredient": "kosher salt"
        },
        "milk":{
            "quantity": 2,
            "unitTag": "cup",
            "ingredient": "milk"
        },
        "egg":{
            "quantity": 3,
            "unitTag": "egg",
            "ingredient": "(large, lightly-beaten)"
        },
        "butter":{
            "quantity": 2,
            "unitTag": "stick",
            "ingredient": "unsalted butter"
        },
        "cheese":{
            "quantity": 16,
            "unitTag": "oz",
            "ingredient": "extra-sharp cheddar (grated)"
        },
        "cheese-inside": {
            "quantity": 8,
            "unitTag": "oz",
            "ingredient": "extra-sharp cheddar (grated)",
            "hidden": true
        },
        "cheese-garnish": {
            "quantity": 8,
            "unitTag": "oz",
            "ingredient": "extra-sharp cheddar (grated)",
            "hidden": true
        },
        "scallions":{
            "quantity": 0.67,
            "unitTag": "cup",
            "ingredient": "scallions (chopped)"
        },
        "jalapeno":{
            "quantity": 3,
            "unitTag": "tbsp",
            "ingredient": "jalapeno (seeded and minced) + 1 whole sliced for garnish"
        }
    },
    "steps": [
        "Combine the flour, cornmeal, sugar, baking powder, and salt in a large bowl. In a separate bowl, combine the milk, eggs, and butter.",
        "With a wooden spoon, stir the wet ingredients into the dry until most of the lumps are dissolved. Don't over mix!",
        "Mix in !cheese-inside, scallions, and jalapenos, and allow the mixture to <b>sit at room temp for 20 minutes</b>.",
        "Preheat the oven to 350Â°F. Grease a 9 x 13 x 2 inch baking pan",
        "Pour the batter into the prepared pan, and smooth the top. Sprinkle !cheese-garnish on the top and the sliced jalapeno. <b>Bake for 30 - 35 minutes, or until the toothpick comes out clean</b>.",
        "Cool and cut into large squares. Serve warm or at room temp."

    ],
    "preptime": "30 min",
    "cooktime": "35 min",
    "totaltime": "1 hr 5 min",
    "serves": 12
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/tiramisu.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Italian Tiramisu",
    "subtitle": "",
    "subtitle2": "",
    "ingredients": {
        "lady-fingers": {
            "quantity": 10,
            "unitTag": "oz",
            "ingredient": "ladyfingers"
        },
        "mascarpone": {
            "quantity": 18,
            "unitTag": "oz",
            "ingredient": "mascarpone cheese"
        },
        "egg": {
            "quantity": 4,
            "unitTag": "egg"
        },
        "sugar": {
            "quantity": 0.67,
            "unitTag": "cup",
            "ingredient": "sugar",
            "override": {
                "triple": "2 cups sugar"
            }
        },
        "water": {
            "quantity": 0.25,
            "unitTag": "cup",
            "ingredient": "water",
            "override": {
                "half": "2 tbsp water"
            }
        },
        "coffee": {
            "quantity": 1,
            "unitTag": "cup",
            "ingredient": "espresso"
        },
        "cocoa-powder": {
            "quantity": 0.25,
            "unitTag": "cup",
            "ingredient": "cocoa powder (Rodelle is my favorite)",
            "override": {
                "half": "2 tbsp cocoa powder (Rodelle is my favorite)"
            }
        }
    },
    "steps": [
        "Brew the espresso and let it cool. For the best tasting tiramisu, choose high quality fresh coffee beans.",
        "Separate the egg yolks and egg whites. Place the egg yolks in a ^large bowl$, and the egg whites in a ^medium steel bowl$.",
        "Place a ^medium saucepan$ on the stove, and add water and sugar. Cook the mixture over medium heat until the sugar is fully dissolved and it comes to a boil. Remove from heat.",
        "Beat the egg yolks just until the yolks are broken up using a ^hand mixer$. While mixing, <b>slowly drizzle</b> in <b>half</b> of the sugar syrup into the mixture. Beat the mixture until it turns pale yellow and doubles in volume.",
        "Add the mascarpone cheese a few tablespoons at a time. Continue beating until a smooth consistency is achieved.",
        "In the medium bowl with the egg whites, begin beating the egg whites using a cleaned hand mixer. Beat until it begins to get slightly frothy. Slowly drizzle in the remaining sugar syrup while beating. Beat until <b>stiff peaks</b> are formed.",
        "Fold in about â…” of the egg white mixture into the egg yolk mixture. Add in small portions until desired consistency. <b>Do not use all as it can become too liquid.</b> <i>Try to be as gentle as possible to not crush the light texture of the egg whites.</i>", 
        "Put the cream mixture in the fridge for at least half an hour.",
        "Add the espresso into a ^shallow dish$. Quickly dip a ladyfinger into the espresso and place in a ^8x8 inch square pan$. Create one layer of ladyfingers.",
        "Spread <b>half</b> the cream mixture on top using an ^offset spatula$. Repeat a layer of ladyfingers then cream.",
        "Dust the top of the tiramisu with the cocoa powder using a ^sieve$.",
        "<b>Refrigerate overnight before serving.</b> <i>This will help the flavors all come together and soak in.</i> If you would like to get the striped design cut some parchment paper into small strips, place on top of the cream and then dust with cocoa."
    ],
    "preptime": "40 min",
    "cooktime": "",
    "totaltime": "40 min",
    "serves": 8
}
