=== anjali-segu/vegetarian-cowgirl/src/assets/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./src/assets/schemas/recipe.schema.json",
  "title": "Recipe",
  "description": "A recipe on The Vegetarian Cowgirl blog",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "description": "Recipe Title",
      "type": "string"
    },
    "subtitle": {
      "description": "Description above the photo",
      "type": "string"
    },
    "subtitle2": {
      "description": "Description below the photo",
      "type": "string"
    },
    "categories": {
      "description": "Recipe categories for steps",
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "description": "Recipe Category",
          "type": "object",
          "properties": {
            "ingredients": {
              "description": "Recipe ingredients per category",
              "type": "object",
              "patternProperties": {
                "^.+$": {
                  "$ref": "ingredient.schema.json"
                }
              },
              "minProperties": 1
            },
            "steps": {
              "description": "Steps per category",
              "type": "array",
              "items": {
                "description": "Step",
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          },
          "required": [
            "ingredients",
            "steps"
          ]
        }
      },
      "minProperties": 1
    },
    "ingredients": {
      "description": "Recipe ingredients",
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "$ref": "ingredient.schema.json"
        }
      },
      "minProperties": 1
    },
    "steps": {
      "description": "Recipe steps",
      "type": "array",
      "items": {
        "description": "Step",
        "type": "string"
      },
      "uniqueItems": true
    },
    "preptime": {
      "description": "How long it takes to prep ingredients",
      "type": "string"
    },
    "cooktime": {
      "description": "How long it takes to cook ingredients",
      "type": "string"
    },
    "totaltime": {
      "description": "Sum of preptime, cooktime, and any additional time for cooling, etc.",
      "type": "string"
    },
    "serves": {
      "type": "integer",
      "minimum": 0,
      "excludeMinimum": true
    }
  },
  "oneOf": [
    {
      "required": [
        "title",
        "subtitle",
        "subtitle2",
        "categories",
        "preptime",
        "cooktime",
        "totaltime",
        "serves"
      ]
    },
    {
      "required": [
        "title",
        "subtitle",
        "subtitle2",
        "ingredients",
        "steps",
        "preptime",
        "cooktime",
        "totaltime",
        "serves"
      ]
    }
  ],
  "additionalProperties": false
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/sugar-cookies.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Soft Sugar Cookie Cutouts",
    "subtitle": "These crisp edged, soft thick centered cookies makes this recipe a must try! Great for any occasion and works well with cutouts.",
    "subtitle2": "These are my favorite sugar cookies with icing! They are almondy, buttery, sweet, and have beautifully soft centers. I normally am not a huge fan of sugar cookies but these have converted me! They are extremely fun to decorate and keep well! Works great for gifts or just for a delcious dessert.",
    "categories": {
        "Cookies": {
            "ingredients": {
                "cookies-flour": {
                    "quantity": 2.25,
                    "unitTag": "cup",
                    "ingredient": "all-purpose flour (spoon & leveled), plus more as needed for rolling and work surface"
                },
                "cookies-baking-powder": {
                    "quantity": 0.5,
                    "unitTag": "tsp",
                    "ingredient": "baking powder"
                },
                "cookies-salt": {
                    "quantity": 0.25,
                    "unitTag": "tsp",
                    "ingredient": "salt"
                },
                "cookies-butter": {
                    "quantity": 0.75,
                    "unitTag": "cup",
                    "ingredient": "unsalted butter, softened to room temperature"
                },
                "cookies-sugar": {
                    "quantity": 0.75,
                    "unitTag": "cup",
                    "ingredient": "granulated sugar"
                },
                "cookies-egg": {
                    "quantity": 1,
                    "unitTag": "large egg"
                },
                "cookies-vanilla": {
                    "quantity": 2,
                    "unitTag": "tsp",
                    "ingredient": "pure vanilla extract"
                },
                "cookies-almond": {
                    "quantity": 0.25,
                    "unitTag": "tsp",
                    "ingredient": "(or double) almond extract (optional, but makes the flavor outstanding)"
                }
            }
        },
        "Icing": {
            "ingredients": {
                "icing-sugar": {
                    "quantity": 3,
                    "unitTag": "cup",
                    "ingredient": "confectioners' sugar"
                },
                "icing-vanilla": {
                    "quantity": 0.5,
                    "unitTag": "tsp",
                    "ingredient": "pure vanilla extract"
                },
                "icing-corn-syrup": {
                    "quantity": 2,
                    "unitTag": "tsp",
                    "ingredient": "light corn syrup"
                },
                "icing-water": {
                    "quantity": 4.5,
                    "unitTag": "tbsp",
                    "ingredient": "(or more) room temperature water"
                },
                "icing-salt": {
                    "ingredient": "pinch of salt"
                }
            }
        }
    },
    "steps": [
        "^Whisk$ the flour, baking powder, and salt together in a ^medium bowl$. Set aside.",
        "In a ^large bowl$ using a ^hand mixer$ or a ^stand mixer$ fitted with a paddle attachment, <b>beat the butter and sugar together on high speed until completely smooth and creamy, about 2 minutes</b>.",
        "Add the egg, vanilla, and almond extract (if using) and beat on high speed until combined, about 1 minute. Scrape down the sides and up the bottom of the bowl and beat again as needed to combine.",
        "Add the dry ingredients to the wet ingredients and mix on low until combined. <b>Dough will be relatively soft</b>. <i>If the dough seems too soft and sticky for rolling, add 1 more Tablespoon of flour</i>.",
        "Divide the dough into 2 equal parts. Place each portion onto a piece of lightly floured parchment paper or a lightly floured ^silicone baking mat$. With a lightly floured ^rolling pin$, roll the dough out to about <b>1/4-inch thickness</b>. Use more flour if the dough seems too sticky. The rolled-out dough can be any shape, as long as it is evenly 1/4-inch thick.",
        "Lightly dust one of the rolled-out doughs with flour. Place a piece of parchment on top. (This prevents sticking.) Place the 2nd rolled-out dough on top. Cover with plastic wrap or aluminum foil, then <b>refrigerate for at least 1-2 hours and up to 2 days</b>.",
        "Once chilled, <b>preheat oven to 350Â°F</b>. Line ^2-3 large baking sheets$ with parchment paper or silicone baking mats. Carefully remove the top dough piece from the refrigerator. If it's sticking to the bottom, run your hand under it to help remove it. Using a ^cookie cutter$, cut the dough into shapes. Re-roll the remaining dough and continue cutting until all is used. Repeat with 2nd piece of dough. (Note: It doesn't seem like a lot of dough, but you get a lot of cookies from the dough scraps you re-roll.)",
        "Arrange cookies on baking sheets <b>3 inches apart</b>. <b>Bake for 11-12 minutes or until lightly browned around the edges</b>. If your oven has hot spots, <b>rotate the baking sheet halfway through bake time</b>. Allow cookies to cool on the baking sheet for 5 minutes then transfer to a ^wire rack$ to cool completely before decorating.",
        "For the frosting, Using a fork, stir the confectioners sugar, vanilla, corn syrup, and !icing-water together in a medium bowl. It will be very thick and almost impossible to stir. Switch to a whisk and whisk in 1/2 Tablespoon (8ml) of water. If you lift the whisk and let the icing drizzle back into the bowl, the ribbon of icing will hold shape for a few seconds before melting back into the icing. That is when you know it's the right consistency and is ready to use. If it's too thick (sometimes it is), whisk in another 1/2 Tablespoon (8ml) of water or a little more until you reach the consistency.",
        "If desired, stir in gel food coloring. You can pour some icing into different bowls if using multiple colors. When tinting icing, only use 1-2 drops at first, stir it in, then add more as needed to reach your desired color. Remember, color darkens as icing dries.",
        "Decorate the cooled cookies with royal icing.",
        "Enjoy cookies right away or wait until the icing sets to serve them. Once the icing has set, these cookies are great for gifting or for sending. Plain or decorated cookies stay soft for about 5 days when covered tightly at room temperature. For longer storage, cover and refrigerate for up to 10 days."
    ],
    "preptime": "2 hrs",
    "cooktime": "12 minutes",
    "totaltime": "4 hrs",
    "serves": 24
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/macaroon.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Raspberry-Rose Jam, Orange Blossom Buttercream Macaron",
    "subtitle": "These macarons have a light orange blossom buttercream with a sharp raspberry rose jam center.",
    "subtitle2": "These macarons always turn out perfectly baked. They are flavored to perfect with the rosewater and orange blossom without being overpowering. While this recipe can be a little tricky, trust me it's worth it!",
    "categories": {
        "Macarons":{
            "ingredients": {
                "almond-flour":{
                    "quantity": 140,
                    "unitTag": "gram",
                    "ingredient": "almond flour"
                },
                "powder-sugar": {
                    "quantity": 140,
                    "unitTag": "gram",
                    "ingredient": "powder sugar"
                },
                "egg-white": {
                    "quantity": 100,
                    "unitTag": "gram",
                    "ingredient": "egg white"
                },
                "egg-white-almond": {
                    "quantity": 50,
                    "unitTag": "gram",
                    "ingredient": "of egg white",
                    "hidden": true
                },
                "egg-white-fluffy": {
                    "quantity": 50,
                    "unitTag": "gram",
                    "ingredient": "of egg white",
                    "hidden": true
                },
                "sugar": {
                    "quantity": 100,
                    "unitTag": "gram",
                    "ingredient": "white sugar"
                },
                "water": {
                    "quantity": 40,
                    "unitTag": "gram",
                    "ingredient": "water"
                },
                "cookie": {
                    "quantity": 60,
                    "unitTag": "cookie",
                    "hidden": true
                }
            }
        },
        "Orange Blossom Buttercream": {
            "ingredients": {
                "butter": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "unsalted butter (room temp)"
                },
                "sugar": {
                    "quantity": 2.5,
                    "unitTag": "cup",
                    "ingredient": "powder sugar"
                },
                "orange-blossom": {
                    "quantity": 2.5,
                    "unitTag": "tsp",
                    "ingredient": "orange blossom water"
                },
                "vanilla": {
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "vanilla extract"
                },
                "heavy-cream": {
                    "quantity": 2,
                    "unitTag": "tbsp",
                    "ingredient": "heavy cream"
                },
                "salt": {
                    "quantity": 1,
                    "unitTag": "pinch",
                    "ingredient": "of salt",
                    "override": {
                        "half": "1 pinch of salt"
                    }
                }
            }
        },
        "Raspberry Rose Jam": {
            "ingredients": {
                "raspberry": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "raspberry (frozen)"
                },
                "sugar": {
                    "quantity": 0.25,
                    "unitTag": "cup",
                    "ingredient": "granulated sugar"
                },
                "water": {
                    "quantity": 1,
                    "unitTag": "tbsp",
                    "ingredient": "water"
                },
                "rose-water": {
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "rose water"
                },
                "salt": {
                    "quantity": 1,
                    "unitTag": "pinch",
                    "ingredient": "of salt",
                    "override": {
                        "half": "1 pinch of salt"
                    }
                }
            }
        }
    },
    "steps": [
        "Line ^2 cookie sheets with parchment paper$",
        "Combine the almond flour and powder sugar. Sift the mixture into a ^large bowl$ to remove any lumps",
        "Add !egg-white-almond and mix into the almond-sugar mixture to form a paste",
        "Add a few drops of pink food gel coloring. <i> This is optional.</i>",
        "In a stand mixer, beat the remaining !egg-white-fluffy <b>until soft peaks form.</b>",
        "Combine the white sugar and water in a ^small saucepan$. Bring to boil over low heat, and heat until it reaches 115°C using a candy thermometer. <b><i>You must use a candy thermometer</i></b>. ",
        "Remove from heat, and slowly drizzle into the ^stand mixer$ with the beaten egg while beating on low speed.",
        "Mix on high for about 3 min or until the bowl is cool and <b>stiff peaks form</b>. You should be able to turn the bowl upside down without the meringue falling out.",
        "<b>Fold the meringue into the almond-sugar paste mixture</b>. Use your spatula to press onto the sides of the bowl to remove any lumps.",
        "Mix until you have a smooth batter that runs off of the spatula slowly in a thick ribbon",
        "Put mixture in ^piping bag$. Pipe small 1 ½ inch circles onto the lined baking tray. I normally get <b>!cookie.</b>",
        "Pipe thre circle by holding the piping bag upright with the tip just above the sheet, and pipe without pulling your hand up or moving it in circles.",
        "Tap the baking sheets a few times on the counter to remove any air bubbles",
        "Let the cookies sit out for 30 minutes to dry",
        "<b>Preheat the oven to 300°F</b>",
        "<b>Bake cookies for 18 min</b>. Remove from the oven and let them completely cool on cooling racks before removing from the parchment paper. <i>They will stick when warm.</i>",
        "<b>To make the buttercream</b>, beat the butter until the butter has lightened and becomes creamy. Add the powder sugar and beat for 5 minutes. Add the orange blossom water, vanilla bean paste, heavy cream and salt and beat for 30 sec.",
        "Fill a piping bag with the buttercream and set aside.",
        "<b>To make the raspberry rose jam</b>, place raspberries, granulated sugar, water, and pinch of salt in a saucepan. Place the saucepan over medium heat. Using a spoon mash up the raspberries. Let the mixture come to a boil and thicken. We want the jam to be quite thick so it doesn't spread. Remove from heat and add the rose water.",
        "<b>To assemble</b>, first pair up all of the macaron halves. Next use a little buttercream and spread on both the top and bottom macaron using a butter knife. Pipe little dots of buttercream around the perimeter of the bottom macaron, leaving a hole in the center. Spoon a little jam into the center. Place the top cookie.",
        "<b>Refridgerate in an air-tight container for at least 1-2 days before serving.</b> <i>This allows the cookies to absorb a little bit of the flavors. Trust me it is worth it!</i>"

        
    ],
    "preptime": "40 min",
    "cooktime": "20 min",
    "totaltime": "1 hr 30 min",
    "serves": 4
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/chocolate-cream-pie.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Chocolate Cream Pie",
    "subtitle": "Using my secret ingredient this recipe comes together in minutes for a quick dessert that satisfies any chocolate lover.",
    "subtitle2": "This silky chocolate cream pie comes together in the blender using silky tofu. Trust me no one will ever know. Every single person who has tried this never knows the secret ingredient. The cream is luscious and has a lovely Kahlua kick. This dessert is so simple to make and always satisfies my chocolate cravings.",
    "ingredients": {
        "chocolate-chips":{
            "quantity": 2,
            "unitTag": "cup",
            "ingredient": "chocolate chips"
        },
        "kahlua":{
            "quantity": 0.33,
            "unitTag": "cup",
            "ingredient": "Kahlua (or any liqueur)"
        },
        "silken-tofu":{
            "quantity": 1,
            "unitTag": "block",
            "ingredient": "silken tofu"
        },
        "vanilla-extract":{
            "quantity": 1,
            "unitTag": "tsp",
            "ingredient": "vanilla extract"
        },
        "honey":{
            "quantity": 1.5,
            "unitTag": "tbsp",
            "ingredient": "honey"
        },
        "crust":{
            "quantity": 1,
            "unitTag": "crust",
            "ingredient": "packaged store-bought chocolate cookie"
        }
    },
    "steps": [
        "Place a ^small metal bowl$ over a ^saucepan$ with simmering water. Melt the chocolate and Kahlua in the bowl. Stir in the vanilla. Remove from heat once completely melt and smooth.",
        "Add the tofu, chocolate mixture, and honey into the ^blender$. Blend until smooth.",
        "Pour the filling into the crust and refrigerate for at least 2 hours, or until the filling is set.",
        "Slice and serve with whipped cream."
    ],
    "preptime": "2 hr 10 min",
    "cooktime": "",
    "totaltime": "2 hr 10 min",
    "serves": 10
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/chocolate-fudge.json
{
    "title": "Grandma Barbieri's Chocolate Fudge",
    "subtitle": "",
    "subtitle2": "",
    "ingredients": {
        "chocolate-chips": {
            "quantity": 12,
            "unitTag": "oz",
            "ingredient": "semisweet chocolate chips (Ghirardelli or Nestle)"
        },
        "condensed-milk": {
            "quantity": 1,
            "unitTag": "can",
            "ingredient": "sweetened condensed milk (not evaporated milk)"
        },
        "vanilla": {
            "quantity": 2,
            "unitTag": "tsp",
            "ingredient": "vanilla"
        }
    },
    "steps": [
        "In a microwave oven, cook chocolate and milk in a large microwave bowl on high (2-3 minutes). Or until chocolate is almost melted. Stir halfway between the melting of the chocolate.",
        "Stir until the chocolate is completely melted. Stir in vanilla (and optionally marshmallows or nuts).",
        "Spread into foil-line, 8-inch square pan.",
        "Refrigerate 2 hours or until firm. Cut into squares."
    ],
    "preptime": "5 min",
    "cooktime": "10 min",
    "totaltime": "2 hr 15 min",
    "serves": 48
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/brownie-ice-cream-sandwiches.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Salted Pecan Brownie Coffee Ice Cream Sandwiches",
    "subtitle": "Love this nostalgic treat? Well, this recipe one-ups that! These ice cream sandwiches are worth every ounce of extra effort. The coffee and chocolate taste work so well together!",
    "subtitle2": "The top and bottom layer of this ice cream dessert is a salted brownie topped with toasted pecans. In the center is a coffee and vanilla swirled ice cream. The brownie stays soft and fudgey even in the freezer. These are an absolute summer hit for your next summer party! Beat the Austin heat with these sweet treats.",
    "ingredients": {
        "chocolate-chips": {
            "quantity": 6,
            "unitTag": "oz",
            "ingredient": "bittersweet chocolate chips (60%)"
        },
        "butter": {
            "quantity": 7.5,
            "unitTag": "tbsp",
            "ingredient": "unsalted butter"
        },
        "canola-oil": {
            "quantity": 3,
            "unitTag": "tbsp",
            "ingredient": "canola oil"
        },
        "sugar": {
            "quantity": 0.375,
            "unitTag": "cup",
            "ingredient": "sugar",
            "override": {
                "whole": "¼ cup + 2 tbsp sugar",
                "half": "3 tbsp sugar",
                "triple": "1 cup + 2 tbsp sugar"
            }
        },
        "egg": {
            "quantity": 3,
            "unitTag": "egg"
        },
        "vanilla-extract": {
            "quantity": 1.5,
            "unitTag": "tsp",
            "ingredient": "vanilla extract"
        },
        "flour": {
            "quantity": 0.75,
            "unitTag": "cup",
            "ingredient": "all purpose flour",
            "override": {
                "half": "¼ cup + 2 tbsp all purpose flour"
            }
        },
        "salt": {
            "quantity": 0.75,
            "unitTag": "tsp",
            "ingredient": "morton kosher salt"
        },
        "pecan": {
            "quantity": 0.33,
            "unitTag": "cup",
            "ingredient": "chopped pecans",
            "override": {
                "half": "3 tbsp chopped pecans"
            }
        },
        "maldon-sea-salt": {
            "quantity": 1,
            "unitTag": "pinch",
            "ingredient": "maldon sea salt"
        },
        "vanilla-ice-cream": {
            "quantity": 1,
            "unitTag": "pint",
            "ingredient": "vanilla ice cream"
        },
        "coffee-ice-cream": {
            "quantity": 2,
            "unitTag": "pint",
            "ingredient": "coffee ice cream"
        }
    },
    "steps": [
        "<b>Preheat the oven to 325°F</b>. Line a ^9 x 13 inch pan$ with foil. Grease thoroughly with baking spray. Set aside.",
        "Place a ^small metal bowl$ on top of ^saucepan$ with simmering water. In the small metal bowl, add the bittersweet chocolate, butter, and oil. Melt until completely smooth. Then remove the bowl from the heat and saucepan.",
        "Beat the eggs and sugar for 1 minute until lighter and frothy with a ^hand mixer$ in a ^large bowl$. Add the vanilla extract and beat for another 30 seconds.",
        "Slowly add the chocolate mixture into the egg mixture while beating. The mixture should thicken up. Then add the flour and kosher salt and combine just until mixed.",
        "Spread half the batter into the pan using an ^offset spatula$. Make sure to level the mixture, as it will bake in this shape. Focus on getting the mix all the way into the corners. Top with maldon sea salt and chopped pecans.",
        "Bake for 9 minutes, or until the top is matte and is not sticky.",
        "Let the first layer cool in pan for 5-10 minutes. Remove the foil with the brownie layer from the pan. Set aside. Put another layer of foil and grease the pan. Spread the other half of the batter evenly in the pan. Bake for 9 minutes.",
        "Remove the layer with the foil from the pan. Let both halves completely cool. Reuse one layer of foil and line the pan. Flip the bottom layer (without toppings) onto the pan so that the top side (matte side) is now facing down. Cover and set in freezer.",
        "Mix your pints of ice cream in a ^large metal bowl$. Mix until a thick sticky batter texture is formed. Remove the pan from the freezer and add the ice cream on top of the bottom brownie layer. Using the offset spatula, smoothen.",
        "Place the top layer on the ice cream, such that the pecans are facing up. Cover and put back in the freezer. Freeze until completely solid (around 4-6 hours).",
        "Remove the pan from the freezer. Using the foil remove the ice cream sandwich brick. Peel off the foil completely. Set the brick on a ^large cutting board$. Using a ^sharp chef's knife$, trim all 4 edges. Keep the edges as a chef's snack.",
        "Cut the rectangle into 3 pieces. Then cut each piece into 4 pieces, creating 12 pieces in total.",
        "Wrap each ice cream sandwich in saran wrap and place into an airtight container. Put the container back into the freezer for 1 hour before serving."
    ],
    "preptime": "20 min",
    "cooktime": "20 min",
    "totaltime": "7 hr 40 min",
    "serves": 12
}
