=== anjali-segu/vegetarian-cowgirl/src/assets/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./src/assets/schemas/recipe.schema.json",
  "title": "Recipe",
  "description": "A recipe on The Vegetarian Cowgirl blog",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "description": "Recipe Title",
      "type": "string"
    },
    "subtitle": {
      "description": "Description above the photo",
      "type": "string"
    },
    "subtitle2": {
      "description": "Description below the photo",
      "type": "string"
    },
    "categories": {
      "description": "Recipe categories for steps",
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "description": "Recipe Category",
          "type": "object",
          "properties": {
            "ingredients": {
              "description": "Recipe ingredients per category",
              "type": "object",
              "patternProperties": {
                "^.+$": {
                  "$ref": "ingredient.schema.json"
                }
              },
              "minProperties": 1
            },
            "steps": {
              "description": "Steps per category",
              "type": "array",
              "items": {
                "description": "Step",
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          },
          "required": [
            "ingredients",
            "steps"
          ]
        }
      },
      "minProperties": 1
    },
    "ingredients": {
      "description": "Recipe ingredients",
      "type": "object",
      "patternProperties": {
        "^.+$": {
          "$ref": "ingredient.schema.json"
        }
      },
      "minProperties": 1
    },
    "steps": {
      "description": "Recipe steps",
      "type": "array",
      "items": {
        "description": "Step",
        "type": "string"
      },
      "uniqueItems": true
    },
    "preptime": {
      "description": "How long it takes to prep ingredients",
      "type": "string"
    },
    "cooktime": {
      "description": "How long it takes to cook ingredients",
      "type": "string"
    },
    "totaltime": {
      "description": "Sum of preptime, cooktime, and any additional time for cooling, etc.",
      "type": "string"
    },
    "serves": {
      "type": "integer",
      "minimum": 0,
      "excludeMinimum": true
    }
  },
  "oneOf": [
    {
      "required": [
        "title",
        "subtitle",
        "subtitle2",
        "categories",
        "preptime",
        "cooktime",
        "totaltime",
        "serves"
      ]
    },
    {
      "required": [
        "title",
        "subtitle",
        "subtitle2",
        "ingredients",
        "steps",
        "preptime",
        "cooktime",
        "totaltime",
        "serves"
      ]
    }
  ],
  "additionalProperties": false
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/cardamom-buns.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Cardamom Buns",
    "subtitle": "This unique twist on a classic dessert is the perfect warm treat! The cardamom flavor works perfectly with the warm vanilla cream cheese glaze.",
    "subtitle2": "This is a new dessert in my house! My mom absolutely loves cardamom as it is a flavor she grew up with in India. Using my cinnamon rolls recipe I substituted the cinnamon for this Indian spice to come up with something new. This was an absolute hit in my family. The sweet yeasty brioche flavor balances the cardamom flavor combined with the creamy sweet frosting. TThe recipe itself is not too hard but will require a stand mixer and some basic dough knowledge.",
    "categories": {
        "Dough": {
            "ingredients": {
                "dough-milk": {
                    "quantity": 1,
                    "unitTag": "cup",
                    "ingredient": "warm milk (115 Degrees F)"
                },
                "dough-yeast": {
                    "quantity": 2.5,
                    "unitTag": "tsp",
                    "ingredient": "instant dry yeast"
                },
                "dough-egg": {
                    "quantity": 2,
                    "unitTag": "egg"
                },
                "dough-butter": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "salted butter, melted and cooled"
                },
                "dough-sugar": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "granulated sugar"
                },
                "dough-salt": {
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "salt"
                },
                "dough-flour": {
                    "quantity": 4,
                    "unitTag": "cup",
                    "ingredient": "all-purpose flour"
                },
                "dough-flour-extra": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "more all-purpose flour (if needed)"
                }
            }
        },
        "Filling": {
            "ingredients": {
                "filling-butter": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "salted butter"
                },
                "filling-sugar": {
                    "quantity": 1,
                    "unitTag": "cup",
                    "ingredient": "packed brown sugar"
                },
                "filling-cardamom": {
                    "quantity": 2,
                    "unitTag": "tbsp",
                    "ingredient": "ground cardamom"
                },
                "filling-cream": {
                    "quantity": 0.5,
                    "unitTag": "cup",
                    "ingredient": "heavy cream"
                }
            }
        },
        "Frosting": {
            "ingredients": {
                "frosting-butter": {
                    "quantity": 0.33,
                    "unitTag": "cup",
                    "ingredient": "salted butter"
                },
                "frosting-cream-cheese":{
                    "quantity": 8,
                    "unitTag": "oz",
                    "ingredient": "cream cheese"
                },
                "frosting-sugar": {
                    "quantity": 2,
                    "unitTag": "cup",
                    "ingredient": "powdered sugar"
                },
                "frosting-vanilla": {
                    "quantity": 2,
                    "unitTag": "tsp",
                    "ingredient": "vanilla extract"
                }
            }
        }
    },
    "steps": [
        "Pour the warm milk in the bowl of a ^stand mixer$ and sprinkle the yeast overtop.",
        "Add the eggs, butter and sugar. Mix until combined.",
        "Add in salt and !dough-flour and mix using the ^beater blade$ just until the ingredients are barely combined. Allow the mixture to rest for 5 minutes so the flour has time to soak up the liquids.",
        "Scrape the dough off the beater blade and remove it. Attach the dough hook.",
        "Beat the dough on medium speed, adding in up to !dough-flour-extra to form a dough. Knead for 5-7 minutes or until the dough is elastic and smooth. <i>The dough should be tacky and will still be sticking to the sides of the bowl. That's ok! Don't be tempted to add more flour at this point. We generally add about 4 ½ cups, but start with 4 cups.</i>",
        "Spray a large bowl with cooking spray.",
        "Use a ^rubber spatula$ to remove the dough from the mixer bowl and place it in the greased large bowl.",
        "Cover the bowl with a ^towel or plastic wrap$.",
        "Set the bowl in a warm place and <b>allow the dough to rise until double</b>. I like to turn on the oven to the lowest setting for 1-2 minutes. Then turn off the oven and place the dough to rise in there. It normally takes about 30 minutes for the dough to rise. Do not allow the dough to rise too much or your cardamom buns will be airy.",
        "While the dough is rising, prepare the cardamom filling. In a medium bowl, combine the soft butter, brown sugar and cardamom, mixing until well combined. Set aside.",
        "Sprinkle a ^silicone mat$ generously with flour. Turn out the dough onto the pastry mat and sprinkle the top of the dough with additional flour.",
        "Flour a ^rolling pin$ and roll the dough to about a <b>24\"  x 15\" rectangle</b>. (the size of the rectangle can vary it does not have to be exact!",
        "Use a rubber spatula to smooth the cardamom filling over the whole dough rectangle.",
        "Starting on the long end, roll the dough up tightly jelly roll style.",
        "Cut into !serves slices and place in a greased ^9 x 13 baking pan$.",
        "Cover the pan and allow the buns to rise for 20 minutes or until nearly double.",
        "<b>Preheat the oven to 375°F</b>.",
        "Warm the heavy cream until the chill is off. Don't make it hot, you just don't want it cold. It should be warm to the touch.",
        "Once the buns have risen, pour the heavy cream over the top of the buns, allowing it to soak down in and around the buns.",
        "Bake at 375°F for 20-22 minutes, until the rols are lightly golden brown and the center buns are cooked through. <i>Note…the time will vary based on how big the buns are, what type of pan, how close the buns are packed, etc</i>. They could take up to 25-27 minutes. Check the buns at 20 minutes. If they are getting too browned, cover loosely with foil for the remaining baking time.",
        "While the buns are cooling, prepare the cream cheese frosting.",
        "In a large bowl, combine the softened cream cheese and butter using a hand mixer or stand mixer. Blend well.",
        "Add in vanilla extract and the powdered sugar. Beat until combined.",
        "Spread the frosting over the cooled buns.",
        "Store in an airtight container."
    ],
    "preptime": "40 min",
    "cooktime": "1 hr 35 min",
    "totaltime": "2 hr 15 min",
    "serves": 12
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/peach-cobbler.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Texas Peach Cobbler",
    "subtitle": "This peach cobbler recipe is only extremely easy to make from scratch. This recipe was inspired from Fredricksburg, TX peaches, but will work with any ripe peach!",
    "subtitle2": "Peach season is pretty much the best time of the year. I enjoy going to “pick your own” farms or buying a large box from a local vendor. In season peaches make this treat absolutely delicious!",
    "categories": {
        "Peach Mixture":{
            "ingredients": {
                "peaches": {
                    "quantity": 5,
                    "unitTag": "peach",
                    "ingredient": "(peeled, cored, and sliced)"
                },
                "sugar": {
                    "quantity": 0.75,
                    "unitTag": "cup",
                    "ingredient": "granulated sugar",
                    "override": {
                        "half": "6 tbsp granulated sugar"
                    }
                },
                "salt": {
                    "quantity": 0.25,
                    "unitTag": "tsp",
                    "ingredient": "salt"
                }
            }
        },
        "Batter": {
            "ingredients": {
                "butter":{
                    "quantity": 6,
                    "unitTag": "tbsp",
                    "ingredient": "butter"
                },
                "flour":{
                    "quantity": 1,
                    "unitTag": "cup",
                    "ingredient": "all-purpose flour"
                },
                "sugar":{
                    "quantity": 1,
                    "unitTag": "cup",
                    "ingredient": "granulated sugar"
                },
                "baking-powder":{
                    "quantity": 2,
                    "unitTag": "tsp",
                    "ingredient": "baking powder"
                },
                "salt":{
                    "quantity": 0.75,
                    "unitTag": "tsp",
                    "ingredient": "salt"
                },
                "milk":{
                    "quantity": 0.75,
                    "unitTag": "cup",
                    "ingredient": "milk",
                    "override": {
                        "half": "6 tbsp milk"
                    }
                },
                "vanilla":{
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "vanilla extract"
                }
            }
        }
    },
    
    "steps": [
        "<b>To prepare the peaches</b>, boil a pot of water. Gently lower 2-3 peaches at a time into a pot of boiling water. Leave them in the water for 30 seconds. Remove and place peaches in ice-water bath. The peach skin can then be peeled off easily. Remove the core and <b>slice into 1 inch thick slices.</b>",
        "Add the sliced peaches, sugar, and salt to a saucepan. Stire to combine. Cook on medium heat for a few minutes, <b>until the sugar is dissolved and helps bring out juices from the peaches</b>. Remove from heat and set aside.",
        "<b>Preheat oven to 350°F</b>. Slice butter into tbsp-size pieces. Add to a 9x13 inch baking dish. Place the pan in the oven while it preheats. All the butter to melt, and <b>remove the pan from the oven once melted.</b>",
        "In a large bowl, mix together the flour, sugar, baking powder, salt, and vanilla. Stir in the milk, until just combines. Pour the mixture into the pan, over the melted butter and smooth it into an even layer.",
        "Spoon the peaches and juice, over the batter.",
        "<b>Bake for 38-40 minutes.</b> Serve warm, with whipped cream, if desired."
    ],
    "preptime": "15 min",
    "cooktime": "40 min",
    "totaltime": "55 min",
    "serves": 9
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/pecan-latte.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Pecan Latte",
    "subtitle": "",
    "subtitle2": "",
    "ingredients": {
        "sugar": {
            "quantity": 0.75,
            "unitTag": "cup",
            "ingredient": "sugar"
        },
        "water": {
            "quantity": 0.5,
            "unitTag": "cup",
            "ingredient": "water"
        },
        "pecan": {
            "quantity": 0.5,
            "unitTag": "cup",
            "ingredient": "toasted and chopped pecans"
        },
        "salt": {
            "quantity": 1,
            "unitTag": "pinch",
            "ingredient": "salt"
        },
        "butter": {
            "quantity": 1,
            "unitTag": "tbsp",
            "ingredient": "butter"
        }
    },
    "steps": [
        "Put the sugar and water in a ^saucepan$. Bring the mixture to boil, then add the pecans and salt.",
        "Let the mixture simmer for 15 minutes. Remove from heat and let the mixture cool. ",
        "Add the mixture to a blender along with the butter. Blend until smooth.",
        "Add 2 tsp into espresso based drinks. Top the drink with some whipped cream, chopped pecans, and drizzle the syrup."
    ],
    "preptime": "5 min",
    "cooktime": "15 min",
    "totaltime": "20 min",
    "serves": 6
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/lava-cake.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Chocolate Lava Cake",
    "subtitle": "This lava cake is the first lava cake to have the perfect gooey center that I am always craving. It is not too sweet and has a decadent chocolate taste.",
    "subtitle2": "This recipe comes together fairly quickly and is always a show stopper when serving to guests. The center is perfectly molten and the cake has a nice strong chocolate flavor. The olive oil has a subtle flavor that works well with the chocolate making this recipe unique.",
    "ingredients": {
        "olive-oil": {
            "quantity": 0.75,
            "unitTag": "cup",
            "ingredient": "olive oil",
            "override": {
                "half": "¼ cup + 2 tbsp olive oil"
            }
        },
        "chocolate": {
            "quantity": 9,
            "unitTag": "oz",
            "ingredient": "bittersweet chocolate chips (60%)"
        },
        "egg-yolks": {
            "quantity": 6,
            "unitTag": "egg",
            "ingredient": "yolks"
        },
        "egg": {
            "quantity": 3,
            "unitTag": "egg"
        },
        "sugar": {
            "quantity": 0.5,
            "unitTag": "cup",
            "ingredient": "sugar"
        },
        "salt": {
            "quantity": 0.5,
            "unitTag": "tsp",
            "ingredient": "Morton kosher salt"
        },
        "vanilla": {
            "quantity": 2,
            "unitTag": "tsp",
            "ingredient": "vanilla extract"
        },
        "flour": {
            "quantity": 2,
            "unitTag": "tbsp",
            "ingredient": "all purpose flour"
        }, 
        "butter": {
            "quantity": 2,
            "unitTag": "tbsp",
            "ingredient": "unsalted butter"
        },
        "mold": {
            "quantity": 8,
            "unitTag": "tin",
            "ingredient": "(6 oz)"
        }
    },
    "steps": [
        "Preheat the oven to 450°F.",
        "<b>Prepare !mold by spreading a thick layer of butter.</b> Make sure to get in all the crevices. My tins were ceramic mini bundt cake molds. Then dust all of the tins with flour and tap out excess flour.",
        "Place a ^steel bowl$ on top of a ^saucepan$ with simmer watering to create a double boiler. Place the chocolate and oil in the bowl. Melt until completely smooth. Then remove from heat and set aside.",
        "Add the whole eggs, egg yolks, sugar, and salt into a ^medium bowl$. Beat using a ^hand mixer$ until the mixture is very pale, thick, and has doubled in volume. This should take around 2 minutes.",
        "Add in the vanilla extract, and flour while beating. Beat until just combined.",
        "Drizzle the egg mixture into the chocolate mixture while beating on low. The mixture should thicken. Beat until just combined.",
        "Pour the mixture equally into all of the molds. Place the molds onto a ^sheet tray$ for easy transportation.",
        "Bake the molds for 15 minutes or until the cakes have puffed, have a matte top, and still have a slightly molten center.",
        "Invert the molds onto a plate, and serve immediately. Top with whipped cream or ice cream."
    ],
    "preptime": "20 min",
    "cooktime": "15 min",
    "totaltime": "35 min",
    "serves": 8
}

=== anjali-segu/vegetarian-cowgirl/src/assets/recipes/gingerbread.json
{
    "$schema": "../schemas/recipe.schema.json",
    "title": "Soft Gingerbread and Royal Icing",
    "subtitle": "This is my favorite gingerbread cookies recipe every holiday season. Soft in the center and perfectly spices. These prep well ahead of time and make perfect treats.",
    "subtitle2": "Gingerbread cookies were something I never truly loved until I made these. I remember as a kid the cookies I always got were hard and crispy. They were heavy on the cinnamon and nothing else. These cookies have a the perfect ginger kick and melt in the mouth. They have soft centers and keep good shape. This past Christmas I decorate these cookies with my entire family and everyone had a blast getting creating and munching on these scrumptious cookies.",
    "categories": {
        "Cookie":{
            "ingredients": {
                "butter":{
                    "quantity": 10,
                    "unitTag": "tbsp",
                    "ingredient": "unsalted butter (softened to room temp)"
                },
                "brown-sugar":{
                    "quantity": 0.75,
                    "unitTag": "cup",
                    "ingredient": "dark brown sugar",
                    "override": {
                    }
                },
                "molasses":{
                    "quantity": 0.67,
                    "unitTag": "cup",
                    "ingredient": "unsulphured molasses"
                },
                "egg":{
                    "quantity": 1,
                    "unitTag": "egg",
                    "ingredient": "(large)"
                },
                "vanilla":{
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "vanilla extract"
                },
                "flour":{
                    "quantity": 3.5,
                    "unitTag": "cup",
                    "ingredient": "all-purpose flour"
                },
                "baking-soda":{
                    "quantity": 1,
                    "unitTag": "tsp",
                    "ingredient": "baking soda"
                },
                "salt":{
                   "quantity": 0.5, 
                   "unitTag": "tsp",
                   "ingredient": "salt" 
                },
                "ginger":{
                    "quantity": 1,
                    "unitTag": "tbsp",
                    "ingredient": "ground ginger"
                },
                "cinnamon":{
                    "quantity": 1,
                    "unitTag": "tbsp",
                    "ingredient": "ground cinnamon"
                },
                "all-spice":{
                    "quantity": 0.5,
                    "unitTag": "tsp",
                    "ingredient": "ground allspice"
                },
                "cloves":{
                    "quantity": 0.5,
                    "unitTag": "tsp",
                    "ingredient": "ground cloves"
                }
            }
        },
        "Icing":{
            "ingredients": {
                "sugar":{
                    "quantity": 2,
                    "unitTag": "cup",
                    "ingredient": "powder sugar (sifted)"
                },
                "meringue-powder":{
                    "quantity": 1.5,
                    "unitTag": "tbsp",
                    "ingredient": "meringue powder (wilton)"
                },
                "water":{
                    "quantity": 4,
                    "unitTag": "tbsp",
                    "ingredient": "water (room temp)"
                }
            }
        }
    },
    "steps": [
        "In a ^large bowl$ using a ^hand-held mixer$ or ^stand mixer$ (paddle attachment), <b>beat butter for 1 minute</b> until it is completely smooth and creamy.",
        "Add the brown sugar and molasses and beat on medium speed until combined and creamy. Scrape down the sides of bowl as needed.",
        "<b>Beat in the egg and vanilla</b> on high speed for <b>2 minutes</b>. If the butter separate that is fine.",
        "In a ^separate bowl$, ^whisk flour$, baking soda, salt, ginger, cinnamon, allspice, and cloves together until combined. Slowly mix the dry ingredients into the wet ingredients until just combined. The dough will be very thick and sticky.",
        "Divide the dough in half and plastic wrap. Wrap each half tightly and create a disc shape. <b>Chill for at least 3 hours and up to 3 days. I like to do overnight</b>.",
        "<b>Preheat oven to 350°F</b>. Line ^2-3 baking$ sheets with parchment or ^silicone baking mats$.",
        "Remove 1 disc of chilled cookie dough from the refrigerator. Generously flour a surface, and rolling pin. Roll out disk until <b>¼ inch thick</b>. Using a ^cookie cutter$, cut into shapes. Place each cookie 1 inch apart. Re-roll the scraps until all the dough is used.",
        "Bake cookies for 9-10 minutes (4 inch cookie cutter) or 11 minutes (larger than 4 inch cookie cutter) or 8 minutes (smaller than 4 inch cookie cutter). Rotate the pan once during baking about halfway through bake time.",
        "All cookies to cool for 5 minutes on the cookie sheet. Transfer to cooling rack using a spatula.",
        "<b>Once complete cooled, the cookies can be decorated.</b>",
        "<b>For the icing</b>, mix powder sugar, meringue powder, and water into a large bowl using a hand mixer or stand mixer (whisk attachment).",
        "Beat icing for <b>2 minutes</b>. When lifting the whisk, the icing should <b>dizzle down and smooth out within 5-10 seconds</b>. If it is too thick, beat in 1 more tablespoon of water at a time.",
        "To create icing for <b>flooding cookies</b>, simply scoop out some icing and add a little water at a time and beat. The icing should drizzle down and smooth out within 1 second.",
        "Add any gel food coloring and beat into the icing until the desired color is achieved.",
        "The icing should dry out in 2-3 hours.",
        "Store cookies in an air-tight container once icing has dried."
    ],
    "preptime": "4 hrs",
    "cooktime": "10 min",
    "totaltime": "6 hrs",
    "serves": 24
}
